# Self deployment of Load Balancer service for pod through yaml file
apiVersion: v1
kind: Service
metadata:
  name: myapp-pod-LoadBalancer
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
    - name: http
      port: 80 # Service port
      targetPort: 80 # Container port
