# Self deploy replica set through yaml file
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: myapp2-rs

spec:
  replicas: 3

  selector:
    matchLabels: 
      app: myapp2

  template: # Pod Template
    metadata: # Dictionary
      name: myapp2-pod
      labels:
        app: myapp2

    spec:
      containers: # List for multi container pods
        - name: myapp2-container
          image: stacksimplify/kubenginx:2.0.0
          ports:
            - containerPort: 80
